apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  my.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    bind-address=0.0.0.0
    binlog-do-db=your_db_name
